# Generated by Django 4.1 on 2023-03-16 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sslcommerz', '0006_payment_prescription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='bank_transaction_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_brand',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_issuer',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_no',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='card_type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='transaction_date',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='val_transaction_id',
        ),
    ]
